#!/bin/sh

#Other
sxhkd &

#Polybar
$HOME/.config/polybar/start.sh
$HOME/.dotfiles/scripts/get_spotify_status.sh

#Wallpaper
feh --bg-tile $HOME/.dotfiles/wallpaper.jpg

#Workspaces
bspc monitor DP-2  -d 1 2 3 4 5
bspc monitor HDMI-1 -d 1 2 3 4 5

bspc config border_width     1
bspc config window_gap      9
bspc config top_padding		20
bspc config left_padding	30
bspc config right_padding	30
bspc config bottom_padding	20

discord --ignore-gpu-blocklist --disable-features=UseOzonePlatform --enable-features=VaapiVideoDecoder --use-gl=desktop --enable-gpu-rasterization --enable-zero-copy
bspc rule -a -o spotify desktop=2
