#!/bin/sh

#Other
sxhkd &

#Polybar
$HOME/.config/polybar/start_primary.sh
#$HOME/.config/polybar/start_secondary.sh

#Wallpaper
feh --bg-tile /home/matteo/Pictures/wallhaven-odx38m.jpg

#Workspaces
bspc monitor DP-2  -d 6 7 8 9 10
bspc monitor HDMI-1 -d 1 2 3 4 5

bspc config border_width     1
bspc config window_gap      9
bspc config top_padding		20
bspc config left_padding	30
bspc config right_padding	30
bspc config bottom_padding	20
